const demo = [
  { src: "https://picsum.photos/id/1/800/600", thumb: "https://picsum.photos/id/1/200/150", type: "image", title: "Mountain", capDesc: "A short description for Mountain." },
  { src: "https://picsum.photos/id/10/800/600", thumb: "https://picsum.photos/id/10/200/150", type: "image", title: "Dog", capDesc: "A short description for Dog." },
  { src: "https://arxiv.org/pdf/2106.01345.pdf", type: "pdf", title: "Sample PDF", capDesc: "A sample PDF document." },
  { src: "https://picsum.photos/id/20/800/600", thumb: "https://picsum.photos/id/20/200/150", type: "image", title: "Forest", capDesc: "A short description for Forest." },
  { src: "https://picsum.photos/id/30/800/600", thumb: "https://picsum.photos/id/30/200/150", type: "image", title: "Beach", capDesc: "A short description for Beach." },
  { src: "https://picsum.photos/id/40/800/600", thumb: "https://picsum.photos/id/40/200/150", type: "image", title: "River", capDesc: "A short description for River." },
  { src: "https://picsum.photos/id/50/800/600", thumb: "https://picsum.photos/id/50/200/150", type: "image", title: "City", capDesc: "A short description for City." },
  { src: "https://picsum.photos/id/60/800/600", thumb: "https://picsum.photos/id/60/200/150", type: "image", title: "Desert", capDesc: "A short description for Desert." },
  { src: "https://picsum.photos/id/70/800/600", thumb: "https://picsum.photos/id/70/200/150", type: "image", title: "Lake", capDesc: "A short description for Lake." },
  { src: "https://picsum.photos/id/80/800/600", thumb: "https://picsum.photos/id/80/200/150", type: "image", title: "Park", capDesc: "A short description for Park." },
  { src: "https://picsum.photos/id/90/800/600", thumb: "https://picsum.photos/id/90/200/150", type: "image", title: "Valley", capDesc: "A short description for Valley." },
  { src: "https://picsum.photos/id/100/800/600", thumb: "https://picsum.photos/id/100/200/150", type: "image", title: "Ocean", capDesc: "A short description for Ocean." },
  { src: "https://picsum.photos/id/110/800/600", thumb: "https://picsum.photos/id/110/200/150", type: "image", title: "Canyon", capDesc: "A short description for Canyon." },
  { src: "https://picsum.photos/id/120/800/600", thumb: "https://picsum.photos/id/120/200/150", type: "image", title: "Plains", capDesc: "A short description for Plains." },
  { src: "https://picsum.photos/id/130/800/600", thumb: "https://picsum.photos/id/130/200/150", type: "image", title: "Hill", capDesc: "A short description for Hill." },
  { src: "https://picsum.photos/id/140/800/600", thumb: "https://picsum.photos/id/140/200/150", type: "image", title: "Waterfall", capDesc: "A short description for Waterfall." },
  { src: "https://picsum.photos/id/150/800/600", thumb: "https://picsum.photos/id/150/200/150", type: "image", title: "Jungle", capDesc: "A short description for Jungle." },
  { src: "https://picsum.photos/id/160/800/600", thumb: "https://picsum.photos/id/160/200/150", type: "image", title: "Savanna", capDesc: "A short description for Savanna." },
  { src: "https://picsum.photos/id/170/800/600", thumb: "https://picsum.photos/id/170/200/150", type: "image", title: "Mountain Range", capDesc: "A short description for Mountain Range." },
  { src: "https://picsum.photos/id/180/800/600", thumb: "https://picsum.photos/id/180/200/150", type: "image", title: "Plateau", capDesc: "A short description for Plateau." },
  { src: "https://picsum.photos/id/190/800/600", thumb: "https://picsum.photos/id/190/200/150", type: "image", title: "Coast", capDesc: "A short description for Coast." },
  { src: "https://picsum.photos/id/200/800/600", thumb: "https://picsum.photos/id/200/200/150", type: "image", title: "Meadow", capDesc: "A short description for Meadow." },
  { src: "https://picsum.photos/id/210/800/600", thumb: "https://picsum.photos/id/210/200/150", type: "image", title: "Glacier", capDesc: "A short description for Glacier." },
  { src: "https://picsum.photos/id/220/800/600", thumb: "https://picsum.photos/id/220/200/150", type: "image", title: "Volcano", capDesc: "A short description for Volcano." },
  { src: "https://picsum.photos/id/230/800/600", thumb: "https://picsum.photos/id/230/200/150", type: "image", title: "Island", capDesc: "A short description for Island." },
  { src: "https://picsum.photos/id/240/800/600", thumb: "https://picsum.photos/id/240/200/150", type: "image", title: "Cave", capDesc: "A short description for Cave." },
  { src: "https://picsum.photos/id/250/800/600", thumb: "https://picsum.photos/id/250/200/150", type: "image", title: "Prairie", capDesc: "A short description for Prairie." },
  { src: "https://arxiv.org/pdf/2106.01346.pdf", type: "pdf", title: "Sample PDF 2", capDesc: "Another sample PDF document." },
];

export default demo;
